# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: /^mp+k$/
email: niboshiporipori@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  mppppk page
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mpppk
github_username:  mpppk

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# ---- for reveal ----
# The Reveal theme
reveal_theme: black.css

# The Reveal transition
reveal_transition: linear

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: /reveal.js/css/theme/ 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: /reveal.js/

# Don't change anything below
# markdown: redcarpet
highlighter: pygments
# markdown_ext: ignoreme

collections:
  books:
    output: true